.TH BANQ-CLI "1" "June 2016" "banq-cli 0.12"
.SH NAME
banq-cli \- a remote procedure call client for Banq Core. 
.SH SYNOPSIS
banq-cli [options] <command> [params] \- Send command to Banq Core. 
.TP
banq-cli [options] help \- Asks Banq Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the banq-cli program. banq-cli is an RPC client used to send commands to Banq Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBbanqd\fP, \fBbanq.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
